spring.application.name=pedidos-service

# H2 embebido
spring.datasource.url=jdbc:h2:mem:pedidos_db;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.sql.init.mode=always

server.port=8080

# Campana Black Friday (usada en la Parte 2)
promo.black-friday.activa=true
